name: Validations

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
  pull_request:
    types:
      - synchronize
      - opened

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: symfonycorp/security-checker-action@v5

  composer:
    runs-on: ubuntu-latest
    container:
      image: crocttech/php-base-image:php8.1-dev
    steps:
      - uses: actions/checkout@v4

      - name: Composer cache
        uses: actions/cache@v3
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/.cache

      - name: Vendor cache
        uses: actions/cache@v3
        with:
          key: vendor-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/vendor

      - name: Tools cache
        uses: actions/cache@v3
        with:
          key: tools
          path: ${{ github.workspace }}/.cache

      - name: Install dependencies
        env:
          COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache
        run: |-
          composer config --global --auth http-basic.croct.repo.repman.io token "${{ secrets.REPMAN_TOKEN }}"
          composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: Validate composer
        env:
          COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache
        run: composer validate

      - name: Normalize composer
        env:
          COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache
        run: composer normalize --dry-run

  phpunit:
    runs-on: ubuntu-latest
    container:
      image: crocttech/php-base-image:php8.1-dev
    steps:
      - uses: actions/checkout@v4

      - name: Composer cache
        uses: actions/cache@v3
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/.cache

      - name: Vendor cache
        uses: actions/cache@v3
        with:
          key: vendor-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/vendor

      - name: Tools cache
        uses: actions/cache@v3
        with:
          key: tools
          path: ${{ github.workspace }}/.cache

      - name: Install dependencies
        env:
          COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache
        run: |-
          composer config --global --auth http-basic.croct.repo.repman.io token "${{ secrets.REPMAN_TOKEN }}"
          composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: phpunit
        run: ./vendor/bin/phpunit --coverage-clover ./coverage.xml

      - uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TESTREPORTER_ID }}
        with:
          coverageCommand: sed -i "s~$(pwd)/~~" coverage.xml
          coverageLocations: ./coverage.xml:clover

  phpstan:
    runs-on: ubuntu-latest
    container:
      image: crocttech/php-base-image:php8.1-dev
    steps:
      - uses: actions/checkout@v4

      - name: Composer cache
        uses: actions/cache@v3
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/.cache

      - name: Vendor cache
        uses: actions/cache@v3
        with:
          key: vendor-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/vendor

      - name: Tools cache
        uses: actions/cache@v3
        with:
          key: tools
          path: ${{ github.workspace }}/.cache

      - name: Install dependencies
        env:
          COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache
        run: |-
          composer config --global --auth http-basic.croct.repo.repman.io token "${{ secrets.REPMAN_TOKEN }}"
          composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: phpstan
        run: ./vendor/bin/phpstan analyse -l max --memory-limit=1G src tests

  phpcs:
    runs-on: ubuntu-latest
    container:
      image: crocttech/php-base-image:php8.1-dev
    steps:
      - uses: actions/checkout@v4

      - name: Composer cache
        uses: actions/cache@v3
        with:
          key: composer-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/.cache

      - name: Vendor cache
        uses: actions/cache@v3
        with:
          key: vendor-${{ hashFiles('**/composer.lock') }}
          path: ${{ github.workspace }}/vendor

      - name: Tools cache
        uses: actions/cache@v3
        with:
          key: tools
          path: ${{ github.workspace }}/.cache

      - name: Install dependencies
        env:
          COMPOSER_CACHE_DIR: ${{ github.workspace }}/.cache
        run: |-
          composer config --global --auth http-basic.croct.repo.repman.io token "${{ secrets.REPMAN_TOKEN }}"
          composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

      - name: phpcs
        run: ./vendor/bin/phpcs -d memory_limit=1G
